// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIGEBOM.Datos.Context;

#nullable disable

namespace SIGEBOM.Datos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SIGEBOM.Datos.Models.Asistencia", b =>
                {
                    b.Property<int>("IdAsistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsistencia"));

                    b.Property<string>("EstadoAsistencia")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Presente");

                    b.Property<DateTime>("FechaHoraRegistro")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("HoraSalida")
                        .HasColumnType("time");

                    b.Property<int>("IdDetalleProgramacionTurno")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdAsistencia");

                    b.HasIndex("IdDetalleProgramacionTurno")
                        .IsUnique();

                    b.HasIndex("IdUsuario");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Bombero", b =>
                {
                    b.Property<int>("IdBombero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBombero"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Activo");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdCargo")
                        .HasColumnType("int");

                    b.Property<int>("IdRango")
                        .HasColumnType("int");

                    b.Property<string>("MotivoEstado")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sexo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TipoSangre")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("IdBombero");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasFilter("[Correo] IS NOT NULL");

                    b.HasIndex("IdCargo");

                    b.HasIndex("IdRango");

                    b.ToTable("Bomberos");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.BomberoCapacitacion", b =>
                {
                    b.Property<int>("IdBomberoCapacitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBomberoCapacitacion"));

                    b.Property<DateTime>("FechaRealizacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdBombero")
                        .HasColumnType("int");

                    b.Property<int>("IdCapacitacion")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdBomberoCapacitacion");

                    b.HasIndex("IdCapacitacion");

                    b.HasIndex("IdBombero", "IdCapacitacion")
                        .IsUnique();

                    b.ToTable("BomberosCapacitaciones");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.BomberoIncidente", b =>
                {
                    b.Property<int>("IdBomberoIncidente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBomberoIncidente"));

                    b.Property<string>("Funcion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdBombero")
                        .HasColumnType("int");

                    b.Property<int>("IdIncidente")
                        .HasColumnType("int");

                    b.HasKey("IdBomberoIncidente");

                    b.HasIndex("IdIncidente");

                    b.HasIndex("IdBombero", "IdIncidente")
                        .IsUnique();

                    b.ToTable("BomberosIncidentes");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Capacitacion", b =>
                {
                    b.Property<int>("IdCapacitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCapacitacion"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Institucion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCapacitacion");

                    b.ToTable("Capacitaciones");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Cargo", b =>
                {
                    b.Property<int>("IdCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCargo"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Activo");

                    b.Property<string>("NombreCargo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCargo");

                    b.HasIndex("NombreCargo")
                        .IsUnique();

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.DetalleInspeccion", b =>
                {
                    b.Property<int>("IdDetalleInspeccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleInspeccion"));

                    b.Property<string>("ElementoRevisado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IdInspeccion")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdDetalleInspeccion");

                    b.HasIndex("IdInspeccion");

                    b.ToTable("DetallesInspecciones");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.DetalleProgramacionTurno", b =>
                {
                    b.Property<int>("IdDetalleProgramacionTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleProgramacionTurno"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Asignado");

                    b.Property<int>("IdBombero")
                        .HasColumnType("int");

                    b.Property<int>("IdProgramacionTurno")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdDetalleProgramacionTurno");

                    b.HasIndex("IdBombero");

                    b.HasIndex("IdProgramacionTurno", "IdBombero")
                        .IsUnique();

                    b.ToTable("DetalleProgramacionTurnos");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Herramienta", b =>
                {
                    b.Property<int>("IdHerramienta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHerramienta"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaAdquisicion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.HasKey("IdHerramienta");

                    b.HasIndex("IdProveedor");

                    b.ToTable("Herramientas");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Incidente", b =>
                {
                    b.Property<int>("IdIncidente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIncidente"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaHoraIncidente")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HoraFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HoraLlegada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HoraSalida")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdLlamada")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoIncidente")
                        .HasColumnType("int");

                    b.HasKey("IdIncidente");

                    b.HasIndex("IdLlamada");

                    b.HasIndex("IdTipoIncidente");

                    b.ToTable("Incidentes");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.InspeccionVehiculo", b =>
                {
                    b.Property<int>("IdInspeccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInspeccion"));

                    b.Property<string>("EstadoGeneral")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Apto");

                    b.Property<DateTime>("FechaHoraInspeccion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdBombero")
                        .HasColumnType("int");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdInspeccion");

                    b.HasIndex("IdBombero");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("InspeccionesVehiculos");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Inventario", b =>
                {
                    b.Property<int>("IdInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInventario"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdHerramienta")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdInventario");

                    b.HasIndex("IdHerramienta");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.LlamadaEmergencia", b =>
                {
                    b.Property<int>("IdLlamada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLlamada"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTipoIncidente")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("NombreReportante")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("IdLlamada");

                    b.HasIndex("IdTipoIncidente");

                    b.HasIndex("IdUsuario");

                    b.ToTable("LlamadasEmergencia");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Mantenimiento", b =>
                {
                    b.Property<int>("IdMantenimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMantenimiento"));

                    b.Property<decimal?>("Costo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("int");

                    b.Property<string>("TipoMantenimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdMantenimiento");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("Mantenimientos");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.ProgramacionTurno", b =>
                {
                    b.Property<int>("IdProgramacionTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProgramacionTurno"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Programado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEncargado")
                        .HasColumnType("int");

                    b.Property<int>("IdTurno")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioCreador")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdProgramacionTurno");

                    b.HasIndex("IdEncargado");

                    b.HasIndex("IdTurno");

                    b.HasIndex("IdUsuarioCreador");

                    b.HasIndex("Fecha", "IdTurno")
                        .IsUnique();

                    b.ToTable("ProgramacionTurnos");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProveedor"));

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("IdProveedor");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Rango", b =>
                {
                    b.Property<int>("IdRango")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRango"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Activo");

                    b.Property<string>("NombreRango")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrdenJerarquico")
                        .HasColumnType("int");

                    b.HasKey("IdRango");

                    b.HasIndex("NombreRango")
                        .IsUnique();

                    b.ToTable("Rangos");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Activo");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRol");

                    b.HasIndex("NombreRol")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.TipoIncidente", b =>
                {
                    b.Property<int>("IdTipoIncidente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoIncidente"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTipoIncidente");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposIncidentes");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Turno", b =>
                {
                    b.Property<int>("IdTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTurno"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Activo");

                    b.Property<TimeSpan>("HoraEntrada")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraSalida")
                        .HasColumnType("time");

                    b.Property<string>("NombreTurno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTurno");

                    b.HasIndex("NombreTurno")
                        .IsUnique();

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Activo");

                    b.Property<int>("IdBombero")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("MotivoEstado")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdBombero")
                        .IsUnique();

                    b.HasIndex("IdRol");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Vehiculo", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVehiculo"));

                    b.Property<int?>("Año")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Activo");

                    b.Property<string>("Marca")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TipoVehiculo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("IdVehiculo");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.VehiculoIncidente", b =>
                {
                    b.Property<int>("IdVehiculoIncidente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVehiculoIncidente"));

                    b.Property<int>("IdIncidente")
                        .HasColumnType("int");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdVehiculoIncidente");

                    b.HasIndex("IdIncidente");

                    b.HasIndex("IdVehiculo", "IdIncidente")
                        .IsUnique();

                    b.ToTable("VehiculosIncidentes");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Asistencia", b =>
                {
                    b.HasOne("SIGEBOM.Datos.Models.DetalleProgramacionTurno", "DetalleProgramacionTurno")
                        .WithOne()
                        .HasForeignKey("SIGEBOM.Datos.Models.Asistencia", "IdDetalleProgramacionTurno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGEBOM.Datos.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DetalleProgramacionTurno");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Bombero", b =>
                {
                    b.HasOne("SIGEBOM.Datos.Models.Cargo", "Cargo")
                        .WithMany("Bomberos")
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SIGEBOM.Datos.Models.Rango", "Rango")
                        .WithMany("Bomberos")
                        .HasForeignKey("IdRango")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Rango");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.BomberoCapacitacion", b =>
                {
                    b.HasOne("SIGEBOM.Datos.Models.Bombero", "Bombero")
                        .WithMany("BomberosCapacitaciones")
                        .HasForeignKey("IdBombero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGEBOM.Datos.Models.Capacitacion", "Capacitacion")
                        .WithMany("BomberosCapacitaciones")
                        .HasForeignKey("IdCapacitacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bombero");

                    b.Navigation("Capacitacion");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.BomberoIncidente", b =>
                {
                    b.HasOne("SIGEBOM.Datos.Models.Bombero", "Bombero")
                        .WithMany("BomberosIncidentes")
                        .HasForeignKey("IdBombero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGEBOM.Datos.Models.Incidente", "Incidente")
                        .WithMany("BomberosIncidentes")
                        .HasForeignKey("IdIncidente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bombero");

                    b.Navigation("Incidente");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.DetalleInspeccion", b =>
                {
                    b.HasOne("SIGEBOM.Datos.Models.InspeccionVehiculo", "InspeccionVehiculo")
                        .WithMany("DetallesInspeccion")
                        .HasForeignKey("IdInspeccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InspeccionVehiculo");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.DetalleProgramacionTurno", b =>
                {
                    b.HasOne("SIGEBOM.Datos.Models.Bombero", "Bombero")
                        .WithMany("ProgramacionesAsignadas")
                        .HasForeignKey("IdBombero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGEBOM.Datos.Models.ProgramacionTurno", "ProgramacionTurno")
                        .WithMany("DetallesProgramacion")
                        .HasForeignKey("IdProgramacionTurno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bombero");

                    b.Navigation("ProgramacionTurno");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Herramienta", b =>
                {
                    b.HasOne("SIGEBOM.Datos.Models.Proveedor", "Proveedor")
                        .WithMany("Herramientas")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Incidente", b =>
                {
                    b.HasOne("SIGEBOM.Datos.Models.LlamadaEmergencia", "LlamadaEmergencia")
                        .WithMany()
                        .HasForeignKey("IdLlamada")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGEBOM.Datos.Models.TipoIncidente", "TipoIncidente")
                        .WithMany("Incidentes")
                        .HasForeignKey("IdTipoIncidente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LlamadaEmergencia");

                    b.Navigation("TipoIncidente");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.InspeccionVehiculo", b =>
                {
                    b.HasOne("SIGEBOM.Datos.Models.Bombero", "Bombero")
                        .WithMany("InspeccionesVehiculos")
                        .HasForeignKey("IdBombero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGEBOM.Datos.Models.Vehiculo", "Vehiculo")
                        .WithMany("InspeccionesVehiculo")
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bombero");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Inventario", b =>
                {
                    b.HasOne("SIGEBOM.Datos.Models.Herramienta", "Herramienta")
                        .WithMany("Inventarios")
                        .HasForeignKey("IdHerramienta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Herramienta");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.LlamadaEmergencia", b =>
                {
                    b.HasOne("SIGEBOM.Datos.Models.TipoIncidente", "TipoIncidente")
                        .WithMany("Llamadas")
                        .HasForeignKey("IdTipoIncidente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGEBOM.Datos.Models.Usuario", "Usuario")
                        .WithMany("LlamadasRegistradas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoIncidente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Mantenimiento", b =>
                {
                    b.HasOne("SIGEBOM.Datos.Models.Vehiculo", "Vehiculo")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.ProgramacionTurno", b =>
                {
                    b.HasOne("SIGEBOM.Datos.Models.Bombero", "Encargado")
                        .WithMany("ProgramacionesComoEncargado")
                        .HasForeignKey("IdEncargado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGEBOM.Datos.Models.Turno", "Turno")
                        .WithMany("ProgramacionesTurno")
                        .HasForeignKey("IdTurno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGEBOM.Datos.Models.Usuario", "UsuarioCreador")
                        .WithMany("ProgramacionesCreadas")
                        .HasForeignKey("IdUsuarioCreador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Encargado");

                    b.Navigation("Turno");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Usuario", b =>
                {
                    b.HasOne("SIGEBOM.Datos.Models.Bombero", "Bombero")
                        .WithOne("Usuario")
                        .HasForeignKey("SIGEBOM.Datos.Models.Usuario", "IdBombero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGEBOM.Datos.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bombero");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.VehiculoIncidente", b =>
                {
                    b.HasOne("SIGEBOM.Datos.Models.Incidente", "Incidente")
                        .WithMany("VehiculosIncidentes")
                        .HasForeignKey("IdIncidente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGEBOM.Datos.Models.Vehiculo", "Vehiculo")
                        .WithMany("VehiculosIncidentes")
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Incidente");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Bombero", b =>
                {
                    b.Navigation("BomberosCapacitaciones");

                    b.Navigation("BomberosIncidentes");

                    b.Navigation("InspeccionesVehiculos");

                    b.Navigation("ProgramacionesAsignadas");

                    b.Navigation("ProgramacionesComoEncargado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Capacitacion", b =>
                {
                    b.Navigation("BomberosCapacitaciones");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Cargo", b =>
                {
                    b.Navigation("Bomberos");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Herramienta", b =>
                {
                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Incidente", b =>
                {
                    b.Navigation("BomberosIncidentes");

                    b.Navigation("VehiculosIncidentes");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.InspeccionVehiculo", b =>
                {
                    b.Navigation("DetallesInspeccion");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.ProgramacionTurno", b =>
                {
                    b.Navigation("DetallesProgramacion");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Proveedor", b =>
                {
                    b.Navigation("Herramientas");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Rango", b =>
                {
                    b.Navigation("Bomberos");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.TipoIncidente", b =>
                {
                    b.Navigation("Incidentes");

                    b.Navigation("Llamadas");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Turno", b =>
                {
                    b.Navigation("ProgramacionesTurno");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Usuario", b =>
                {
                    b.Navigation("LlamadasRegistradas");

                    b.Navigation("ProgramacionesCreadas");
                });

            modelBuilder.Entity("SIGEBOM.Datos.Models.Vehiculo", b =>
                {
                    b.Navigation("InspeccionesVehiculo");

                    b.Navigation("Mantenimientos");

                    b.Navigation("VehiculosIncidentes");
                });
#pragma warning restore 612, 618
        }
    }
}
